# Site settings
title: ronygomes.me
email: rgomes.bd@gmail.com
description: >-
  Its not a tutorial website with article, its actually learning notes for future myself.
baseurl: ""
url: "http://ronygomes.me"
github_username: ronygomes

# Build settings
permalink: /:title:output_ext
markdown: kramdown
theme: minima
