# Site settings
title: ronygomes.me
email: rgomes.bd@gmail.com
description: Learning notes for future myself
baseurl: ""
url: "http://ronygomes.me"
github_username: ronygomes
image_cdn_root: https://media.publit.io/file/1d4b

# Build settings
permalink: /:title:output_ext
markdown: kramdown
theme: minima
